# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('death_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Author_Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LitWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('wrote_date', models.CharField(blank=True, max_length=50)),
                ('wrote_date_type', models.BooleanField(default=True)),
                ('wrote_date_source', models.CharField(blank=True, max_length=150, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_published_alive', models.BooleanField(default=False)),
                ('publish_title', models.CharField(blank=True, max_length=100, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('publisher_title', models.CharField(blank=True, max_length=100, null=True)),
                ('publish_pages', models.CharField(blank=True, max_length=20, null=True)),
                ('archive_title', models.CharField(blank=True, max_length=100, null=True)),
                ('is_main_version', models.BooleanField(default=False)),
                ('version_type', models.CharField(choices=[('MN', 'Основная редакция'), ('DF', 'Черновик'), ('ED', 'Редакция'), ('LS', 'Список')], default='MN', max_length=50)),
                ('work_status', models.CharField(choices=[('PB', 'Опубликовано'), ('UPB', 'Не опубликовано'), ('LCK', 'Защищено авторским правом')], default='PB', max_length=50)),
                ('is_editable', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.Collection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent_Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_version', to='cabinet.LitWork')),
                ('main_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_version', to='cabinet.LitWork')),
            ],
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='author_work',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.LitWork'),
        ),
    ]
